### ISSUE TITLE
Error when install sphinx.themes.plone 0.1.1 from PYPI

### ISSUE THREAD

**Issue by macagua** [plone/sphinx.themes.plone#27] opened 2015-03-09 13:30 UTC
Hi @loechel and @2svx

I have a Error when install sphinx.themes.plone 0.1.1 from PYPI into a virtualenv with Python 2.7

```
macagua@dacagua:~/proyectos/plone/git/Covantec/training$ virtualenv leo --python=/usr/bin/python2.7
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in leo/bin/python2.7
Also creating executable in leo/bin/python
Installing setuptools............done.
Installing pip...............done.
macagua@dacagua:~/proyectos/plone/git/Covantec/training$ source leo/bin/activate
(leo)macagua@dacagua:~/proyectos/plone/git/Covantec/training$ pip install sphinx.themes.plone
Downloading/unpacking sphinx.themes.plone
  Downloading sphinx.themes.plone-0.1.1.tar.gz (952kB): 952kB downloaded
  Running setup.py egg_info for package sphinx.themes.plone
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_2to3'
      warnings.warn(msg)
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./leo/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg (from sphinx.themes.plone)
Downloading/unpacking Sphinx (from sphinx.themes.plone)
  Downloading Sphinx-1.3b3.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py egg_info for package Sphinx
    
    warning: no files found matching 'TODO'
    no previously-included directories found matching 'doc/_build'
Downloading/unpacking docutils (from sphinx.themes.plone)
  Downloading docutils-0.12.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py egg_info for package docutils
    
    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Downloading/unpacking Pygments (from sphinx.themes.plone)
  Downloading Pygments-2.0.2.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py egg_info for package Pygments
    
Downloading/unpacking six>=1.4 (from Sphinx->sphinx.themes.plone)
  Downloading six-1.9.0.tar.gz
  Running setup.py egg_info for package six
    
    no previously-included directories found matching 'documentation/_build'
Downloading/unpacking Jinja2>=2.3 (from Sphinx->sphinx.themes.plone)
  Downloading Jinja2-2.7.3.tar.gz (378kB): 378kB downloaded
  Running setup.py egg_info for package Jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking snowballstemmer>=1.1 (from Sphinx->sphinx.themes.plone)
  Downloading snowballstemmer-1.2.0.tar.gz (49kB): 49kB downloaded
  Running setup.py egg_info for package snowballstemmer
    
    warning: no files found matching '*.py' under directory 'src'
Downloading/unpacking babel (from Sphinx->sphinx.themes.plone)
  Downloading Babel-1.3.tar.gz (3.4MB): 3.4MB downloaded
  Running setup.py egg_info for package babel
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
Downloading/unpacking alabaster (from Sphinx->sphinx.themes.plone)
  Downloading alabaster-0.7.1.tar.gz
  Running setup.py egg_info for package alabaster
    
    warning: no files found matching 'README.md'
    warning: no previously-included files matching '.*.swp' found under directory 'alabaster'
Downloading/unpacking sphinx-rtd-theme (from Sphinx->sphinx.themes.plone)
  Downloading sphinx_rtd_theme-0.1.6.tar.gz (217kB): 217kB downloaded
  Running setup.py egg_info for package sphinx-rtd-theme
    
Downloading/unpacking markupsafe (from Jinja2>=2.3->Sphinx->sphinx.themes.plone)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py egg_info for package markupsafe
    
Downloading/unpacking pytz>=0a (from babel->Sphinx->sphinx.themes.plone)
  Downloading pytz-2014.10.tar.bz2 (166kB): 166kB downloaded
  Running setup.py egg_info for package pytz
    
Installing collected packages: sphinx.themes.plone, Sphinx, docutils, Pygments, six, Jinja2, snowballstemmer, babel, alabaster, sphinx-rtd-theme, markupsafe, pytz
  Running setup.py install for sphinx.themes.plone
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_2to3'
      warnings.warn(msg)
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    Skipping installation of /home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site-packages/sphinx/__init__.py (namespace package)
    Skipping installation of /home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site-packages/sphinx/themes/__init__.py (namespace package)
    Installing /home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site-packages/sphinx.themes.plone-0.1.1-py2.7-nspkg.pth
  Running setup.py install for Sphinx
    /home/macagua/proyectos/plone/git/Covantec/training/leo/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/sdist.py:5: UserWarning: Module sphinx was already imported from None, but /home/macagua/proyectos/plone/git/Covantec/training/leo/build/Sphinx is being added to sys.path
    
    warning: no files found matching 'TODO'
    no previously-included directories found matching 'doc/_build'
    Installing sphinx-apidoc script to /home/macagua/proyectos/plone/git/Covantec/training/leo/bin
    Installing sphinx-build script to /home/macagua/proyectos/plone/git/Covantec/training/leo/bin
    Installing sphinx-quickstart script to /home/macagua/proyectos/plone/git/Covantec/training/leo/bin
    Installing sphinx-autogen script to /home/macagua/proyectos/plone/git/Covantec/training/leo/bin
  Running setup.py install for docutils
    Traceback (most recent call last):
      File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 699, in <module>
        main()
      File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 679, in main
        paths_in_sys = addsitepackages(paths_in_sys)
      File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 282, in addsitepackages
        addsitedir(sitedir, known_paths)
      File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 204, in addsitedir
        addpackage(sitedir, name, known_paths)
      File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 173, in addpackage
        exec(line)
      File "<string>", line 1, in <module>
    KeyError: 'sphinx'
    Complete output from command /home/macagua/proyectos/plone/git/Covantec/training/leo/bin/python2.7 -c "import setuptools;__file__='/home/macagua/proyectos/plone/git/Covantec/training/leo/build/docutils/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-v8WrXj-record/install-record.txt --single-version-externally-managed --install-headers /home/macagua/proyectos/plone/git/Covantec/training/leo/include/site/python2.7:
    Traceback (most recent call last):

  File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 699, in <module>

    main()

  File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 679, in main

    paths_in_sys = addsitepackages(paths_in_sys)

  File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 282, in addsitepackages

    addsitedir(sitedir, known_paths)

  File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 204, in addsitedir

    addpackage(sitedir, name, known_paths)

  File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 173, in addpackage

    exec(line)

  File "<string>", line 1, in <module>

KeyError: 'sphinx'

----------------------------------------
Command /home/macagua/proyectos/plone/git/Covantec/training/leo/bin/python2.7 -c "import setuptools;__file__='/home/macagua/proyectos/plone/git/Covantec/training/leo/build/docutils/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-v8WrXj-record/install-record.txt --single-version-externally-managed --install-headers /home/macagua/proyectos/plone/git/Covantec/training/leo/include/site/python2.7 failed with error code 1 in /home/macagua/proyectos/plone/git/Covantec/training/leo/build/docutils
Storing complete log in /home/macagua/.pip/pip.log
```

Any idea what happen?

**Comment by plone-foundation** [comment] 2015-03-09 14:46
Hi,

yeah we know, you should not use the version on pypi, even better
someone should remove the whole package from there, I just use the
source and mr.developer.
The version on pypi is also really really old.

Cheers,


SVen

**Comment by macagua** [comment] 2015-03-09 15:37
hi @plone-foundation 

Then install from github repo with the following command and I have the same error:

```
$ pip install git+https://github.com/plone/sphinx.themes.plone.git
Downloading/unpacking git+https://github.com/plone/sphinx.themes.plone.git
  Cloning https://github.com/plone/sphinx.themes.plone.git to /tmp/pip-_FkR9O-build
  Running setup.py egg_info for package from git+https://github.com/plone/sphinx.themes.plone.git
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_2to3'
      warnings.warn(msg)
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./leo/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg (from sphinx.themes.plone==0.2.0dev)
Downloading/unpacking Sphinx (from sphinx.themes.plone==0.2.0dev)
  Downloading Sphinx-1.3b3.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py egg_info for package Sphinx
    
    warning: no files found matching 'TODO'
    no previously-included directories found matching 'doc/_build'
Downloading/unpacking docutils (from sphinx.themes.plone==0.2.0dev)
  Downloading docutils-0.12.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py egg_info for package docutils
    
    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Downloading/unpacking Pygments (from sphinx.themes.plone==0.2.0dev)
  Downloading Pygments-2.0.2.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py egg_info for package Pygments
    
Downloading/unpacking six>=1.4 (from Sphinx->sphinx.themes.plone==0.2.0dev)
  Downloading six-1.9.0.tar.gz
  Running setup.py egg_info for package six
    
    no previously-included directories found matching 'documentation/_build'
Downloading/unpacking Jinja2>=2.3 (from Sphinx->sphinx.themes.plone==0.2.0dev)
  Downloading Jinja2-2.7.3.tar.gz (378kB): 378kB downloaded
  Running setup.py egg_info for package Jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking snowballstemmer>=1.1 (from Sphinx->sphinx.themes.plone==0.2.0dev)
  Downloading snowballstemmer-1.2.0.tar.gz (49kB): 49kB downloaded
  Running setup.py egg_info for package snowballstemmer
    
    warning: no files found matching '*.py' under directory 'src'
Downloading/unpacking babel (from Sphinx->sphinx.themes.plone==0.2.0dev)
  Downloading Babel-1.3.tar.gz (3.4MB): 3.4MB downloaded
  Running setup.py egg_info for package babel
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
Downloading/unpacking alabaster (from Sphinx->sphinx.themes.plone==0.2.0dev)
  Downloading alabaster-0.7.1.tar.gz
  Running setup.py egg_info for package alabaster
    
    warning: no files found matching 'README.md'
    warning: no previously-included files matching '.*.swp' found under directory 'alabaster'
Downloading/unpacking sphinx-rtd-theme (from Sphinx->sphinx.themes.plone==0.2.0dev)
  Downloading sphinx_rtd_theme-0.1.6.tar.gz (217kB): 217kB downloaded
  Running setup.py egg_info for package sphinx-rtd-theme
    
Downloading/unpacking markupsafe (from Jinja2>=2.3->Sphinx->sphinx.themes.plone==0.2.0dev)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py egg_info for package markupsafe
    
Downloading/unpacking pytz>=0a (from babel->Sphinx->sphinx.themes.plone==0.2.0dev)
  Downloading pytz-2014.10.tar.bz2 (166kB): 166kB downloaded
  Running setup.py egg_info for package pytz
    
Installing collected packages: Sphinx, docutils, Pygments, sphinx.themes.plone, six, Jinja2, snowballstemmer, babel, alabaster, sphinx-rtd-theme, markupsafe, pytz
  Running setup.py install for Sphinx
    
    warning: no files found matching 'TODO'
    no previously-included directories found matching 'doc/_build'
    Installing sphinx-apidoc script to /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin
    Installing sphinx-build script to /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin
    Installing sphinx-quickstart script to /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin
    Installing sphinx-autogen script to /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin
  Running setup.py install for docutils
    changing mode of build/scripts-2.7/rst2html.py from 644 to 755
    changing mode of build/scripts-2.7/rst2s5.py from 644 to 755
    changing mode of build/scripts-2.7/rst2latex.py from 644 to 755
    changing mode of build/scripts-2.7/rst2xetex.py from 644 to 755
    changing mode of build/scripts-2.7/rst2man.py from 644 to 755
    changing mode of build/scripts-2.7/rst2xml.py from 644 to 755
    changing mode of build/scripts-2.7/rst2pseudoxml.py from 644 to 755
    changing mode of build/scripts-2.7/rstpep2html.py from 644 to 755
    changing mode of build/scripts-2.7/rst2odt.py from 644 to 755
    changing mode of build/scripts-2.7/rst2odt_prepstyles.py from 644 to 755
    
    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
    changing mode of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/rst2odt_prepstyles.py to 755
    changing mode of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/rst2man.py to 755
    changing mode of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/rstpep2html.py to 755
    changing mode of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/rst2xml.py to 755
    changing mode of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/rst2odt.py to 755
    changing mode of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/rst2latex.py to 755
    changing mode of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/rst2xetex.py to 755
    changing mode of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/rst2html.py to 755
    changing mode of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/rst2pseudoxml.py to 755
    changing mode of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/rst2s5.py to 755
  Running setup.py install for Pygments
    
    Installing pygmentize script to /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin
  Running setup.py install for sphinx.themes.plone
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_2to3'
      warnings.warn(msg)
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    Skipping installation of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site-packages/sphinx/__init__.py (namespace package)
    Skipping installation of /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site-packages/sphinx/themes/__init__.py (namespace package)
    Installing /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site-packages/sphinx.themes.plone-0.2.0dev-py2.7-nspkg.pth
  Running setup.py install for six
    Traceback (most recent call last):
      File "/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site.py", line 699, in <module>
        main()
      File "/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site.py", line 679, in main
        paths_in_sys = addsitepackages(paths_in_sys)
      File "/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site.py", line 282, in addsitepackages
        addsitedir(sitedir, known_paths)
      File "/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site.py", line 204, in addsitedir
        addpackage(sitedir, name, known_paths)
      File "/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site.py", line 173, in addpackage
        exec(line)
      File "<string>", line 1, in <module>
    KeyError: 'sphinx'
    Complete output from command /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/python -c "import setuptools;__file__='/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/build/six/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1ubmcj-record/install-record.txt --single-version-externally-managed --install-headers /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/include/site/python2.7:
    Traceback (most recent call last):

  File "/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site.py", line 699, in <module>

    main()

  File "/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site.py", line 679, in main

    paths_in_sys = addsitepackages(paths_in_sys)

  File "/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site.py", line 282, in addsitepackages

    addsitedir(sitedir, known_paths)

  File "/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site.py", line 204, in addsitedir

    addpackage(sitedir, name, known_paths)

  File "/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/lib/python2.7/site.py", line 173, in addpackage

    exec(line)

  File "<string>", line 1, in <module>

KeyError: 'sphinx'

----------------------------------------
Command /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/bin/python -c "import setuptools;__file__='/home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/build/six/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1ubmcj-record/install-record.txt --single-version-externally-managed --install-headers /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/include/site/python2.7 failed with error code 1 in /home/macagua/proyectos/plone/git/Covantec/training/_build/latex/leo/build/six
Storing complete log in /home/macagua/.pip/pip.log
```

What are the specific Sphinx versions that you have tried this package?

**Comment by polyester** [comment] 2015-03-09 16:12
Hi @macagua, pin your Sphinx. You're downloading a beta of 1.3.x, try sticking with current stable (1.2.3, even a little lower like 1.2.1 works)

**Comment by macagua** [comment] 2015-03-09 18:21
Hi @polyester 
cc @plone-foundation 

I am trying to install Sphinx, as your recommend me into a virtualenv with Python 2.7, with these command:

**Installing Sphinx 1.2.3**
```
pip install "Sphinx==1.2.3"
pip install git+https://github.com/plone/sphinx.themes.plone.git
```

**Installing Sphinx 1.2.1**
```
pip install "Sphinx==1.2.1"
pip install git+https://github.com/plone/sphinx.themes.plone.git
```

I have the same error:

```
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Traceback (most recent call last):
  File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 699, in <module>
    main()
  File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 679, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/macagua/proyectos/plone/git/Covantec/training/leo/lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyError: 'sphinx'
make: *** [html] Error 1
```

**Comment by svx** [comment] 2015-03-10 06:13
I do no get why you try this via pip, I ,mean sure yu can try it, but the theme never got tested against pip.

We use buildout and mr,developer and it just works fine, you should make sure that you have installed all dependencies, best place to look is https://github.com/plone/papyrus/blob/master/buildout.cfg.

Further on, after the install you want to configure the theme, like which version of plone, version switcher and so on and so on.

**Comment by aclark4life** [comment] 2015-03-10 11:24
@macagua This is almost certainly an issue with your environment, and **not an issue with pip, sphinx.themes.plone or buildout vs. pip**. I can't reproduce:

```

alexclark@MH01936711MACDT:/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/ > virtualenv .
New python executable in ./bin/python2.7
Also creating executable in ./bin/python
Installing setuptools, pip...done.
alexclark@MH01936711MACDT:/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/ > bin/pip install sphinx.themes.plone
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Collecting sphinx.themes.plone
  Downloading sphinx.themes.plone-0.1.1.tar.gz (952kB)
    100% |################################| 954kB 521kB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./lib/python2.7/site-packages (from sphinx.themes.plone)
Collecting Sphinx (from sphinx.themes.plone)
  Using cached Sphinx-1.2.3-py2-none-any.whl
Collecting docutils (from sphinx.themes.plone)
  Using cached docutils-0.12.tar.gz
Collecting Pygments (from sphinx.themes.plone)
  Using cached Pygments-2.0.2-py2-none-any.whl
Collecting Jinja2>=2.3 (from Sphinx->sphinx.themes.plone)
  Using cached Jinja2-2.7.3.tar.gz
Collecting markupsafe (from Jinja2>=2.3->Sphinx->sphinx.themes.plone)
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: markupsafe, Jinja2, Pygments, docutils, Sphinx, sphinx.themes.plone
  Running setup.py install for markupsafe
    building 'markupsafe._speedups' extension
    clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c markupsafe/_speedups.c -o build/temp.macosx-10.9-x86_64-2.7/markupsafe/_speedups.o
    clang -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.9-x86_64-2.7/markupsafe/_speedups.o -o build/lib.macosx-10.9-x86_64-2.7/markupsafe/_speedups.so
  Running setup.py install for Jinja2

  Running setup.py install for docutils
    changing mode of build/scripts-2.7/rst2html.py from 644 to 755
    changing mode of build/scripts-2.7/rst2s5.py from 644 to 755
    changing mode of build/scripts-2.7/rst2latex.py from 644 to 755
    changing mode of build/scripts-2.7/rst2xetex.py from 644 to 755
    changing mode of build/scripts-2.7/rst2man.py from 644 to 755
    changing mode of build/scripts-2.7/rst2xml.py from 644 to 755
    changing mode of build/scripts-2.7/rst2pseudoxml.py from 644 to 755
    changing mode of build/scripts-2.7/rstpep2html.py from 644 to 755
    changing mode of build/scripts-2.7/rst2odt.py from 644 to 755
    changing mode of build/scripts-2.7/rst2odt_prepstyles.py from 644 to 755
    changing mode of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/bin/rst2html.py to 755
    changing mode of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/bin/rst2latex.py to 755
    changing mode of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/bin/rst2man.py to 755
    changing mode of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/bin/rst2odt.py to 755
    changing mode of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/bin/rst2odt_prepstyles.py to 755
    changing mode of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/bin/rst2pseudoxml.py to 755
    changing mode of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/bin/rst2s5.py to 755
    changing mode of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/bin/rst2xetex.py to 755
    changing mode of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/bin/rst2xml.py to 755
    changing mode of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/bin/rstpep2html.py to 755

  Running setup.py install for sphinx.themes.plone
    Skipping installation of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/lib/python2.7/site-packages/sphinx/__init__.py (namespace package)
    Skipping installation of /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/lib/python2.7/site-packages/sphinx/themes/__init__.py (namespace package)
    Installing /private/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpuU9ncA/lib/python2.7/site-packages/sphinx.themes.plone-0.1.1-py2.7-nspkg.pth
Successfully installed Jinja2-2.7.3 Pygments-2.0.2 Sphinx-1.2.3 docutils-0.12 markupsafe-0.23 sphinx.themes.plone-0.1.1
```

I would upgrade your pip, virtualenv, setuptools, etc and try again.

**Comment by svx** [comment] 2015-04-17 12:20
closing now, feel free to reopen !

**Closed by svx** 2015-04-17 12:20 UTC
Labels: bug
